// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type Amenity struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Provider   string    `json:"provider"`
	CreatedAt  time.Time `json:"created_at"`
	Category   string    `json:"category"`
	UpdatedAt  time.Time `json:"updated_at"`
	PropertyID int64     `json:"property_id"`
}

type Bedroom struct {
	ID             int64     `json:"id"`
	BedroomNumber  int32     `json:"bedroom_number"`
	EnSuite        bool      `json:"en_suite"`
	Master         bool      `json:"master"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	PropertyUnitID int64     `json:"property_unit_id"`
}

type Property struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Town       string    `json:"town"`
	PostalCode string    `json:"postal_code"`
	Type       string    `json:"type"`
	MinPrice   int32     `json:"min_price"`
	MaxPrice   int32     `json:"max_price"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	CreatedBy  int64     `json:"created_by"`
}

type PropertyUnit struct {
	ID         int64     `json:"id"`
	Bathrooms  int32     `json:"bathrooms"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	PropertyID int64     `json:"property_id"`
}

type Tenant struct {
	ID             int64        `json:"id"`
	StartDate      time.Time    `json:"start_date"`
	EndDate        sql.NullTime `json:"end_date"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	PropertyUnitID int64        `json:"property_unit_id"`
}

type User struct {
	ID         int64          `json:"id"`
	Email      sql.NullString `json:"email"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Phone      sql.NullString `json:"phone"`
	Onboarding sql.NullBool   `json:"onboarding"`
	Avatar     sql.NullString `json:"avatar"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
