# An official Go runtime
FROM golang:1.19

ENV DBDRIVER=postgres
ENV DBHOST=nyatta-dev.cckkqsgzkqfg.us-east-1.rds.amazonaws.com
ENV DBPORT=5432
ENV DBNAME=nyatta-dev
ENV DBUSER=postgres
ENV DBPASS=u49B3pmART1lzjGMeZ9V
ENV DBSSLMODE=disable
# Server
ENV SERVERPORT=4000
# Server env
ENV SERVERENV=development
# Jwt
ENV JWTEXPIRE=3600s
# generated by - (pwgen -s -1 64)
ENV JWTSECRET=t95xjRO2nWOnfj4HdxgrXKwHSzOl6DOmgyA919pk2PUofbBrsgQRwvptzcbVmDP3

# Create an application directory
RUN mkdir -p go/src/app

# Set working directory to /go/src/app
WORKDIR go/src/app

# Copy current dir contents into the container at go/src/app
COPY . go/src/app
COPY go.mod go/src/app
COPY go.sum go/src/app

# Build the Go app
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o nyatta

# Expose port 4000
EXPOSE 4000

# Run the command be default when container starts
CMD ["./nyatta"]
