CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  subscribe_retries INTEGER NOT NULL DEFAULT 0,
  next_renewal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  phone VARCHAR(15) UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS caretakers (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL UNIQUE,
  verified BOOLEAN NOT NULL DEFAULT false,
  created_by uuid REFERENCES users ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS properties (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  location GEOMETRY(POINT, 4326) NOT NULL,
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by uuid REFERENCES users ON DELETE SET NULL ON UPDATE CASCADE,
  caretaker_id uuid REFERENCES caretakers ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS property_units (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  type VARCHAR(100) NOT NULL,
  state VARCHAR(50) NOT NULL DEFAULT 'VACANT',
  price INTEGER NOT NULL,
  bathrooms INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  property_id uuid REFERENCES properties ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS amenities (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  provider VARCHAR(100) NOT NULL DEFAULT '',
  category VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  property_unit_id uuid REFERENCES property_units ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tenants (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  property_unit_id uuid REFERENCES property_units ON DELETE SET NULL,
  user_id uuid REFERENCES users ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bedrooms (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  bedroom_number INTEGER NOT NULL,
  en_suite BOOLEAN NOT NULL DEFAULT false,
  master BOOLEAN NOT NULL DEFAULT false,
  property_unit_id uuid NOT NULL REFERENCES property_units ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS uploads (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  upload TEXT NOT NULL,
  category VARCHAR(100) NOT NULL,
  label VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  property_unit_id uuid REFERENCES property_units ON DELETE CASCADE,
  property_id uuid REFERENCES properties ON DELETE CASCADE,
  user_id uuid REFERENCES users ON DELETE CASCADE,
  caretaker_id uuid REFERENCES caretakers ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shoots (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  shoot_date TIMESTAMP NOT NULL,
  property_id uuid NOT NULL REFERENCES properties ON DELETE CASCADE,
  property_unit_id uuid NOT NULL REFERENCES property_units ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  caretaker_id uuid NOT NULL REFERENCES caretakers ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mailings (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  email VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  msid VARCHAR(15),
  channel VARCHAR(100),
  currency TEXT,
  bank TEXT,
  auth_code TEXT,
  country_code VARCHAR(5),
  fees money,
  amount money,
  phone VARCHAR(15) REFERENCES users(phone) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL DEFAULT 'PROCESSING',
  reference VARCHAR(20),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
