DELETE FROM users CASCADE;
DELETE FROM properties CASCADE;
DELETE FROM amenities CASCADE;
DELETE FROM property_units CASCADE;
DELETE FROM tenants CASCADE;
DELETE FROM bedrooms CASCADE;
DELETE FROM caretakers CASCADE;
DELETE FROM shoots CASCADE;
