ALTER TABLE properties
DROP COLUMN IF EXISTS min_price,
DROP COLUMN IF EXISTS max_price;

ALTER TABLE properties
ADD COLUMN IF NOT EXISTS caretaker BIGINT REFERENCES caretakers ON DELETE CASCADE;

ALTER TABLE properties
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'pending';
