ALTER TABLE amenities
ALTER COLUMN provider
DROP NOT NULL;

ALTER TABLE amenities
DROP COLUMN IF EXISTS property_id CASCADE;

ALTER TABLE amenities
ADD COLUMN IF NOT EXISTS property_unit_id BIGINT NOT NULL REFERENCES property_units ON DELETE CASCADE;
