package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/3dw1nM0535/nyatta/graph/generated"
	"github.com/3dw1nM0535/nyatta/graph/model"
	"github.com/google/uuid"
)

// ID is the resolver for the id field.
func (r *amenityResolver) ID(ctx context.Context, obj *model.Amenity) (uuid.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UnitID is the resolver for the unitId field.
func (r *amenityResolver) UnitID(ctx context.Context, obj *model.Amenity) (*uuid.UUID, error) {
	panic(fmt.Errorf("not implemented: UnitID - unitId"))
}

// Amenity returns generated.AmenityResolver implementation.
func (r *Resolver) Amenity() generated.AmenityResolver { return &amenityResolver{r} }

type amenityResolver struct{ *Resolver }
