package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/3dw1nM0535/nyatta/graph/generated"
	"github.com/3dw1nM0535/nyatta/graph/model"
)

// User is the resolver for the user field.
func (r *tenantResolver) User(ctx context.Context, obj *model.Tenant) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// PropertyUnit is the resolver for the propertyUnit field.
func (r *tenantResolver) PropertyUnit(ctx context.Context, obj *model.Tenant) (*model.PropertyUnit, error) {
	panic(fmt.Errorf("not implemented: PropertyUnit - propertyUnit"))
}

// Tenant returns generated.TenantResolver implementation.
func (r *Resolver) Tenant() generated.TenantResolver { return &tenantResolver{r} }

type tenantResolver struct{ *Resolver }
